#!/bin/bash
touch .flaskenv
echo 'set FLASK_APP=run.py'>>.flaskenv
echo 'set FLASK_ENV="development"'>>.flaskenv
echo 'set SECRET_KEY="justarandomkey"'>>.flaskenv
echo 'set SQLALCHEMY_DATABASE_URI="sqlite:///site.db"'>>.flaskenv
echo 'set EMAIL_USER="'$1'"'>>.flaskenv
echo 'set EMAIL_PASS="'$2'"'>>.flaskenv
py -3 -m venv venv
pip install -r requirements.txt
